### PR TITLE
Fix compile with Qt5.14.0

### PR DESCRIPTION
**Pull request by NSUTanghaixiang**
Add version judgment on some obsolete interfaces

### CODE REVIEW

**Comment by danvratil** [comment]
Hello. We do not accept patches through Github, this is just a mirror. Please submit a patch through our Gitlab instance here: https://invent.kde.org

Thanks!

**Comment by NSUTanghaixiang** [comment]
Only the debian folder, how should I submit the patch？

**Comment by danvratil** [comment]
Please see https://community.kde.org/Get_Involved for more details how to contribute the patch. Thank you!

**Comment by tsdgeos** [comment]
Thanks for your contribution :)

This repository is a mirror of a KDE repository. This means that developers are not looking at pull requests created in GitHub, so I'm closing this pull request (actually a bot is doing it).
Please see https://community.kde.org/Infrastructure/Github_Mirror for details on how to contribute to this and other KDE projects.

**Pull request closed without merging**
